In [2]:
import numpy as np

In [3]:
a=np.arange(6)
a.shape

(6,)

In [4]:
a=np.zeros(5)
print(type(a[0]))

<class 'numpy.float64'>


In [5]:
b=np.zeros((4,))
print(b,b.shape,b.dtype)

[0. 0. 0. 0.] (4,) float64


In [6]:
c=np.random.rand(4);print(c)

[0.58731956 0.11453034 0.13745989 0.07889199]


In [7]:
d=np.arange(4);print(d)

[0 1 2 3]


Indexing in numpy arrays

In [8]:
a=np.arange(10)
print(a)
print(a[2].shape,a[1])
print(f"a[-1]={a[-1]}")
try:
    c=a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
() 1
a[-1]=9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### Slicing in numpy arrays

In [9]:
b=np.arange(10)
print(b)
c=b[2:7:1]
print(c)
print(b[1:10:2])
print(b[:10:2])
print(b[:])
print(b[:-1])
print(b[:-2])
print(b[:-3])
print(b[::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[1 3 5 7 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]


### Single vector operartions

In [10]:
d=np.array([1,2,3,4])
print(d)
#to negate the elementsof the d
e=-d
print(e)
#sum  of all elements 
e=np.sum(d)
print(e)
e=np.mean(d)
print(e)
e=d**2
print(e)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


Vector vector element wise operations

In [11]:
a=np.array([1,2,3,4])
b=np.array([-1,-2,-3,-4])
print(a+b)
print(f"The addition works as")

[0 0 0 0]
The addition works as


scalar vector element wise operations

In [12]:
a=np.array([1,2,3,4])

#multiply a by a scalar

b=5*a
print(b)

[ 5 10 15 20]


Vector dot product

In [13]:
def dot(a,b):
    x=0
    for i in range(a.shape[0]):
        x=x+a[i]*b[i]
    return x
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(dot(a,b))

30


In [14]:
a=np.array([[1,2],[2,3]])
print(a[0])
print(a[1])
print(a[1].shape[0])#accessing the seocnd array size


[1 2]
[2 3]
2


In [15]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.dot(a,b)
print(c)
c=np.dot(b,a)
print(c)

30
30


Time diffeence between loop vs vector

In [16]:
import time
np.random.seed(1)
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(f"{c:.4f}")
print(f"{1000*(toc-tic):.4f}")

249825.0234
43.8192


In [17]:
tic=time.time()
c=dot(a,b)
toc=time.time()
print(f"{c:.4f}")
print(f"{1000*(toc-tic):.4f}")

249825.0234
719.1460


In [18]:
x=np.array([[1],[2],[3],[4]])
w=np.array([2])
print(x[1])
c=np.dot(x[1],w)
print(x[1].shape[0])
print(w.shape)
print(c.shape)

[2]
1
(1,)
()


In [19]:
print(len(["u"," i""j","k""l"]))

3


In [20]:
a=np.zeros((1,5))
print(f"{a.shape},s={a}")
a=np.zeros((4,1))
print(f"{a.shape},a={a}")
a=np.random.random_sample((1,1))
print(f"a_shape={a.shape},a={a}")

(1, 5),s=[[0. 0. 0. 0. 0.]]
(4, 1),a=[[0.]
 [0.]
 [0.]
 [0.]]
a_shape=(1, 1),a=[[0.03762516]]


In [21]:
a=np.array([[5],[4],[3]])
print(a.shape,a)

(3, 1) [[5]
 [4]
 [3]]


In [22]:
a=np.array([[5],
            [4],
            [3]])
print(a.shape,a)

(3, 1) [[5]
 [4]
 [3]]


In [23]:
a=np.arange(6).reshape(-1,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [24]:
print(a[0,0],a[0,1])
print(a[1,0],a[1,1])
print(a[2,0],a[2,1])
print(a[2].shape)
print(a[1].shape)

0 1
2 3
4 5
(2,)
(2,)


In [25]:
a=np.arange(20).reshape(-1,10)
print(a)
print(a[0,2:7:1],a[0,2:7:1].shape[0]) #to print length of array
print(a[1,2:7:1],a[1,2:7:1].shape)
print(a[:,:])
print(a[::])
print(a[1,:])
print(a[0,:])
print(a[0])
print(a[1])


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[2 3 4 5 6] 5
[12 13 14 15 16] (5,)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
