In [6]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.12.0'

In [8]:
rank_0=tf.constant(4)
print(rank_0)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
rank_1=tf.constant([2.0,3.0,4.0])
print(rank_1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [10]:
rank_2=tf.constant([[1,2],
                    [3,4],
                    [5,6]],dtype=tf.float16)
print(rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [14]:
rank_2.dtype,rank_2.shape

(tf.float16, TensorShape([3, 2]))

In [15]:
a=tf.constant([[1,2],
               [3,4]])
b=tf.constant([[1,1],
               [1,1]])
print(tf.add(a,b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [16]:
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [18]:
print(tf.matmul(a,b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [19]:
print(a+b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [20]:
print(a-b)

tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [21]:
print(tf.reduce_max(rank_2))

tf.Tensor(6.0, shape=(), dtype=float16)


In [22]:
print(tf.math.argmax(rank_2))

tf.Tensor([2 2], shape=(2,), dtype=int64)


In [23]:
print(tf.nn.softmax(rank_2))

tf.Tensor(
[[0.269 0.731]
 [0.269 0.731]
 [0.269 0.731]], shape=(3, 2), dtype=float16)


In [25]:
print(tf.convert_to_tensor([1,2,3]))pr

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [28]:

print(tf.reduce_max([1,2,3]))

tf.Tensor(3, shape=(), dtype=int32)


In [30]:
print(tf.reduce_max(np.array([1,2,3])))

tf.Tensor(3, shape=(), dtype=int64)


In [32]:
rank_4=tf.zeros([3,2,4,5])
print(rank_4)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [33]:
tf.rank(rank_4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [35]:
tf.shape(rank_4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>